name: Argocd

on:
  workflow_call:
    inputs:
      yq_version:
        type: string
        description: 'yq version'
        default: 'v4.35.1'
        required: false  
      tag:
        type: string
        description: 'Image tag'
        required: true
      image:
        type: string
        description: 'Image name'
        required: true
        
jobs:
  argocd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
    - name: Setup yq
      run: |
             curl -LO https://github.com/mikefarah/yq/releases/download/${{ inputs.yq_version }}/yq_linux_amd64
             chmod +x yq_linux_amd64
             mv yq_linux_amd64 yq
             sudo mv yq /usr/local/bin/
             
    - name: 🚀  Deploy ArgoCD to Homologacao
      run: |

        export TAG=${{ inputs.tag }}
        export IMAGE=${{ inputs.image }}
             
        yq eval -i '.superchart-app.tag = env(TAG)' charts/values-hom.yaml
        yq eval -i '.superchart-app.image = env(IMAGE)' charts/values-hom.yaml

        echo "Tag changed"     
        cat charts/values-hom.yaml

        git config --local user.name dataom-bot
        git config --local user.email bot@dataom.com.br
        git add charts/values-hom.yaml
        git commit -m "🖉 Update homolog changelog with ${GITHUB_REF#refs/*/}"
        git push

    - name: 🚀  Deploy ArgoCD to Production
      run: |

        export TAG=${{ inputs.tag }}
        export IMAGE=${{ inputs.image }}
             
        yq eval -i '.superchart-app.tag = env(TAG)' charts/values-prod.yaml
        yq eval -i '.superchart-app.image = env(IMAGE)' charts/values-prod.yaml

        echo "Tag changed"     
        cat charts/values-prod.yaml

        git config --local user.name dataom-bot
        git config --local user.email bot@dataom.com.br
        git add charts/values-prod.yaml
        git commit -m "🖉 Update production changelog with ${GITHUB_REF#refs/*/}"
        git push
