name: CI

on:
  workflow_call:
    inputs:
      dockerfile_path:
        type: string
        description: 'Caminho para o docker file'
        required: false
        default: '.'
      image:
        type: string
        description: 'Repositorio'
        required: false
        default: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
    outputs:
      tag:
        description: "Id da tag"
        value: ${{ jobs.build.outputs.tag }}
      image:
        description: "noma da imagem"
        value: ${{ jobs.build.outputs.image }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: docker
    outputs:
      image: ${{ steps.build_push.outputs.image }}
      tag: ${{ steps.build_push.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }} 
    - name: Docker build and push
      id: build_push
      run: |
           IMAGE=${{ inputs.image }}
           REPOSITORY="${{ secrets.AZURE_ACR_URL }}/${{ inputs.image }}"
           TAG="${GITHUB_SHA::7}"
           echo "image=$IMAGE" >> $GITHUB_OUTPUT
           echo "tag=$TAG" >> $GITHUB_OUTPUT
           
#           docker build -t $REPOSITORY:$TAG -t $REPOSITORY:latest . -f ${{ inputs.dockerfile_path }}/Dockerfile
#           docker push $REPOSITORY:$TAG 
#           docker push $REPOSITORY:latest 
