name: CI

on:
  workflow_call:
    inputs:
      dockerfile_path:
        type: string
        description: 'Caminho para o docker file'
        required: false
        default: '.'
      repository:
        type: string
        description: 'Repositorio'
        required: false
        default: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/} 
        #${{ github.repository }}
    outputs:
      repository:
        description: "Repositorio"
        value: ${{ jobs.build.outputs.repository }}
      tag:
        description: "Id da tag"
        value: ${{ jobs.build.outputs.tag }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker build
    outputs:
      repository: ${{ steps.build_push.outputs.repository }}
      tag: ${{ steps.build_push.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }} 
    - name: Docker build and push
      id: build_push
      run: |
           DATE=$(date +'%Y%m%d')
           REPOSITORY="${{ secrets.AZURE_ACR_URL }}/$GITHUB_REPOSITORY_OWNER"
           TAG="${GITHUB_SHA::7}"

           REPO_NAME=${{ inputs.repository }}
           echo $REPO_NAME
#           docker build -t $REPOSITORY:$TAG -t $REPOSITORY:latest . -f ${{ inputs.dockerfile_path }}/Dockerfile
#           docker push $REPOSITORY:$TAG 
#           docker push $REPOSITORY:latest 
          
#           echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT
#           echo "tag=$TAG" >> $GITHUB_OUTPUT
